production:
  adapter: mysql2
  database: edrs_dc_remote
  username: root
  password: Mnzysk123
  host: localhost
  pool: 500

development:
  adapter: mysql2
  database: edrs_dc_remote
  username: root
  password: Mnzysk123
  host: localhost
  pool: 500